// golden-fixture parity: the ts engine must reproduce the numbers of the
// VERBATIM swift SleepMetricsAnalyzer (expected outputs generated by
// tests/parity-harness/, see its main.swift). a mismatch is a port bug.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { SleepMetricsAnalyzer } from '@/domain/metrics/analyzer';
import { dayKey } from '@/domain/session-rules';
import type { SleepSession } from '@/domain/models';

const FIXTURES = [
  'regular-sleeper',
  'shift-worker',
  'timezone-traveler',
  'sub-5-min-noise',
  'gaps-streaks',
];

interface FixtureSession {
  id: string;
  tag: string;
  startTime: number;
  endTime: number | null;
  startTz: string;
  endTz: string | null;
}

function load(name: string): { input: any; expected: any } {
  const dir = join(__dirname, 'fixtures');
  return {
    input: JSON.parse(readFileSync(join(dir, `${name}.json`), 'utf8')),
    expected: JSON.parse(readFileSync(join(dir, `${name}-expected.json`), 'utf8')),
  };
}

function toSessions(raw: FixtureSession[]): SleepSession[] {
  return raw.map((s) => ({
    id: s.id,
    tag: s.tag,
    startTime: s.startTime,
    endTime: s.endTime,
    startTimeZone: s.startTz,
    endTimeZone: s.endTz,
    createdAt: 0,
    updatedAt: 0,
  }));
}

// swift doubles and js doubles may differ in the last ulps through exp/pow
const EPS = 1e-9;

function expectClose(actual: number | null, expected: number | null, label: string) {
  if (expected == null || actual == null) {
    expect({ [label]: actual }).toEqual({ [label]: expected });
    return;
  }
  const scale = Math.max(1, Math.abs(expected));
  if (Math.abs(actual - expected) > EPS * scale) {
    throw new Error(`${label}: expected ${expected}, got ${actual}`);
  }
}

describe.each(FIXTURES)('golden fixture parity: %s', (name) => {
  const { input, expected } = load(name);
  const analyzer = new SleepMetricsAnalyzer(toSessions(input.sessions), {
    optimalSleepMinutes: input.optimalSleepMinutes,
    optimalWakeMinutes: input.optimalWakeMinutes,
    // fixed reference day; none of the compared metrics depend on it
    today: { year: 2025, month: 6, day: 1 },
  });
  const records = analyzer.records;

  test('night records match (dates, weekdays, offsets)', () => {
    expect(records).toHaveLength(expected.records.length);
    records.forEach((r, i) => {
      const e = expected.records[i];
      expect(dayKey(r.date)).toBe(e.date);
      expect(r.weekday).toBe(e.weekday);
      expectClose(r.durationHours, e.durationHours, `records[${i}].durationHours`);
      expectClose(r.bedtimeOffset, e.bedtimeOffset, `records[${i}].bedtimeOffset`);
      expectClose(r.wakeOffset, e.wakeOffset, `records[${i}].wakeOffset`);
      expectClose(r.midpointOffset, e.midpointOffset, `records[${i}].midpointOffset`);
    });
  });

  test('targets match', () => {
    expectClose(analyzer.targetDurationHours, expected.targetDurationHours, 'targetDurationHours');
    expectClose(analyzer.targetSleepOffset, expected.targetSleepOffset ?? null, 'targetSleepOffset');
    expectClose(analyzer.targetWakeOffset, expected.targetWakeOffset ?? null, 'targetWakeOffset');
  });

  test('scalar metrics match', () => {
    expectClose(analyzer.averageDuration(records), expected.averageDuration ?? null, 'averageDuration');
    expectClose(analyzer.medianDuration(records), expected.medianDuration ?? null, 'medianDuration');
    expectClose(analyzer.totalSleepHours(records), expected.totalSleepHours, 'totalSleepHours');
    expectClose(analyzer.longestNight(records), expected.longestNight ?? null, 'longestNight');
    expectClose(analyzer.shortestNight(records), expected.shortestNight ?? null, 'shortestNight');
    expect(analyzer.goalHitRate(records)).toBe(expected.goalHitRate);
    expectClose(
      analyzer.durationTrendPercent(records),
      expected.durationTrendPercent ?? null,
      'durationTrendPercent'
    );
    expect(analyzer.sleepConsistencyScore(records)).toBe(expected.sleepConsistencyScore);
    expect(analyzer.wakeConsistencyScore(records)).toBe(expected.wakeConsistencyScore);
    expect(analyzer.scheduleAccuracyScore(records)).toBe(expected.scheduleAccuracyScore);
    expect(analyzer.regularityScore(records)).toBe(expected.regularityScore);
    expectClose(analyzer.socialJetlagHours(records), expected.socialJetlagHours ?? null, 'socialJetlagHours');
    expectClose(analyzer.cumulativeDebtHours(records), expected.cumulativeDebtHours, 'cumulativeDebtHours');
  });

  test('moving average series matches', () => {
    const series = analyzer.movingAverageSeries(records);
    expect(series).toHaveLength(expected.movingAverageSeries.length);
    series.forEach((p, i) => {
      const e = expected.movingAverageSeries[i];
      expect(dayKey(p.date)).toBe(e.date);
      expectClose(p.durationHours, e.durationHours, `movingAvg[${i}].durationHours`);
      expectClose(p.movingAverageHours, e.movingAverageHours ?? null, `movingAvg[${i}].avg`);
    });
  });

  test('rolling consistency series matches', () => {
    const series = analyzer.rollingConsistencySeries(records);
    expect(series).toHaveLength(expected.rollingConsistencySeries.length);
    series.forEach((p, i) => {
      const e = expected.rollingConsistencySeries[i];
      expect(dayKey(p.date)).toBe(e.date);
      expect(p.sleepConsistency).toBe(e.sleepConsistency ?? null);
      expect(p.wakeConsistency).toBe(e.wakeConsistency ?? null);
      expect(p.scheduleAccuracy).toBe(e.scheduleAccuracy ?? null);
    });
  });

  test('cumulative debt series matches', () => {
    const series = analyzer.cumulativeDebtSeries(records);
    expect(series).toHaveLength(expected.cumulativeDebtSeries.length);
    series.forEach((p, i) => {
      const e = expected.cumulativeDebtSeries[i];
      expect(dayKey(p.date)).toBe(e.date);
      expectClose(p.cumulativeHours, e.cumulativeHours, `debt[${i}]`);
    });
  });

  test('duration trends analysis matches', () => {
    const trends = analyzer.durationTrendsAnalysis();
    expect(trends).toHaveLength(expected.durationTrendsAnalysis.length);
    trends.forEach((t, i) => {
      const e = expected.durationTrendsAnalysis[i];
      expect(t.days).toBe(e.days);
      expectClose(t.averageDuration, e.averageDuration ?? null, `trend[${i}].avg`);
      expectClose(t.previousAverageDuration, e.previousAverageDuration ?? null, `trend[${i}].prev`);
      expectClose(t.changePercent, e.changePercent ?? null, `trend[${i}].change`);
      expect(t.sparkline).toHaveLength(e.sparkline.length);
      t.sparkline.forEach((v, j) => expectClose(v, e.sparkline[j], `trend[${i}].spark[${j}]`));
    });
  });

  test('weekday averages match', () => {
    const averages = analyzer.weekdayAverages(records);
    averages.forEach((w, i) => {
      const e = expected.weekdayAverages[i];
      expect(w.weekday).toBe(e.weekday);
      expect(w.dayName).toBe(e.dayName);
      expect(w.nights).toBe(e.nights);
      expectClose(w.averageHours, e.averageHours, `weekday[${i}]`);
    });
  });

  test('duration buckets match', () => {
    const buckets = analyzer.durationBuckets(records);
    buckets.forEach((b, i) => {
      const e = expected.durationBuckets[i];
      expect(b.label).toBe(e.label);
      expect(b.count).toBe(e.count);
      expectClose(b.share, e.share, `bucket[${i}]`);
    });
  });

  test('sleep alignment series matches', () => {
    const series = analyzer.sleepAlignmentSeries(records);
    expect(series).toHaveLength(expected.sleepAlignmentSeries.length);
    series.forEach((p, i) => {
      const e = expected.sleepAlignmentSeries[i];
      expect(dayKey(p.date)).toBe(e.date);
      expectClose(p.dailyScore, e.dailyScore, `align[${i}].daily`);
      expectClose(p.trendScore, e.trendScore, `align[${i}].trend`);
      expectClose(p.durationScore, e.durationScore, `align[${i}].duration`);
      expectClose(p.timingScore, e.timingScore, `align[${i}].timing`);
      expectClose(p.phaseScore, e.phaseScore, `align[${i}].phase`);
      expectClose(p.consistencyScore, e.consistencyScore, `align[${i}].consistency`);
    });
  });
});
